module:
  theme: "up-business-theme"
  languageCode: "en-us"
  module.hugoVersion:
    extended: true
    min: "0.115.4"

title: "ATLAS DIGITAL"

summaryLength: 20

params:
  title: "Atlas Digital"
  description: "We specialize in providing services to design websites, applications, build and maintain businesses for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Morocco, Marrakech"
    - "Sweden, Stockholm"

  contact:
    - "atlasdigital@gmail.com"

  copyright: "© 2024 All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/how-we-work/process"
      weight: 2

    - name: "Our team"
      url: "/our-team"
      weight: 3
    - name: "Blog"
      url: "/blog"
      weight: 4

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/how-we-work/process"


    - name: "Our team"
      url: "#"
      weight: 3

  

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
